kind: pipeline
name: default

steps:
- name: all-examples
  image: circleci/openjdk:8-jdk
  user: root
  environment:
    BAZEL_VERSION: 0.27.0
    CHECKOUT_DIR: /drone/src
    GENERIC_PROJECTS_DIR: $CHECKOUT_DIR/generic
    JAVA_PROJECTS_DIR: $CHECKOUT_DIR/java
  commands:
  # Install Bazel
  - sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python3
  - wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh"
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh
  - export PATH="$PATH:$HOME/bin"
  
  # Execute projects using generic functionality
  - cd $GENERIC_PROJECTS_DIR/tar; bazel build //:my-tar
  - cd $GENERIC_PROJECTS_DIR/rules/print-message; bazel build //:nothing
  - cd $GENERIC_PROJECTS_DIR/rules/write-file; bazel build //:gen
  
  # Execute Java-based projects
  - cd $JAVA_PROJECTS_DIR/single-package; bazel build //:hello-world