dist: xenial
sudo: required
language: java

before_install:
  - sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python3
  - wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/0.27.0/bazel-0.27.0-installer-linux-x86_64.sh"
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh

script:
  - cd java
  - cd single-package; bazel build //:hello-world
  - cd ..; cd multi-package; bazel build //:hello-world
  - cd ..; cd multi-module; bazel build //app:app
  - cd ..; cd external-deps; bazel build //:app
  - cd ..; cd compile-only-dep; bazel build //:lib
  - cd ..; cd junit4-test; bazel test //:all-tests --test_output=all
  - cd ..; cd javadoc; bazel build //:app-doc
  - cd ..; cd versioned-java-library; bazel build //:messenger