dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.27.0/bazel_0.27.0-linux-x86_64.deb
  - sudo dpkg -i bazel_0.27.0-linux-x86_64.deb

script:
  - cd java/single-package; bazel build //:hello-world