dist: xenial
sudo: required

osx_image: xcode8.3
language: java

before_install:
  - sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python3
  - wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/0.27.0/bazel-0.27.0-installer-linux-x86_64.sh"
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh

script:
  - cd java/single-package; bazel build //:hello-world
  - cd java/multi-package; bazel build //:hello-world
  - cd java/multi-module; bazel build //app:app
  - cd java/external-deps; bazel build //:app
  - cd java/compile-only-dep; bazel build //:lib
  - cd java/junit-4; bazel test //:all-tests --test_output=all
  - cd java/javadoc; bazel build //:javadoc
  - cd java/versioned-java-library; bazel build //:messenger