version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.6
    steps:
      - checkout
      - run:
          name: Execute Sample Projects
          command: |-
              # Set environment variables
              export BAZEL_VERSION=0.27.0
              export CHECKOUT_DIR=${HOME}/project
              export GENERIC_PROJECTS_DIR=${CHECKOUT_DIR}/generic
              export JAVA_PROJECTS_DIR=${CHECKOUT_DIR}/java

              # Install Bazel
              sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python3
              wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh"
              chmod +x install.sh
              ./install.sh --user
              rm -f install.sh
              export PATH="$PATH:$HOME/bin"

              # Execute projects using generic functionality
              cd $GENERIC_PROJECTS_DIR/tar; bazel build //:my-tar
              cd $GENERIC_PROJECTS_DIR/rules/print-message; bazel build //:nothing
              cd $GENERIC_PROJECTS_DIR/rules/write-file; bazel build //:gen

              # Execute Java-based projects
              - cd $JAVA_PROJECTS_DIR/single-package; bazel build //:hello-world
              - cd $JAVA_PROJECTS_DIR/multi-package; bazel build //:hello-world
              - cd $JAVA_PROJECTS_DIR/multi-module; bazel build //app:app
              - cd $JAVA_PROJECTS_DIR/external-deps; bazel build //:app
              - cd $JAVA_PROJECTS_DIR/compile-only-dep; bazel build //:lib
              - cd $JAVA_PROJECTS_DIR/pom-generation; bazel build //:pom
              - cd $JAVA_PROJECTS_DIR/junit4-test; bazel test //:all-tests --test_output=all
              - cd $JAVA_PROJECTS_DIR/junit5-test; bazel test //:junit5-test --test_output=all
              - cd $JAVA_PROJECTS_DIR/jacoco-test-coverage; bazel test //:all-tests --test_output=all
              - cd $JAVA_PROJECTS_DIR/javadoc; bazel build //:app-doc
              - cd $JAVA_PROJECTS_DIR/versioned-java-library; bazel build //:messenger
              - cd $JAVA_PROJECTS_DIR/spring-boot; bazel build //:spring-boot-hello-world
              - cd $JAVA_PROJECTS_DIR/spring-boot-in-docker-image; bazel build //:app-image
              - cd $JAVA_PROJECTS_DIR/web-app-in-docker-image; bazel build //:docker-image