version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Execute Sample Projects
          command: |-
              # Set environment variables
              export BAZEL_VERSION=1.1.0
              export CHECKOUT_DIR=${HOME}/project
              export GENERIC_PROJECTS_DIR=${CHECKOUT_DIR}/generic
              export JAVA_PROJECTS_DIR=${CHECKOUT_DIR}/java

              # Install Bazel
              sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python3
              wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh"
              chmod +x install.sh
              ./install.sh --user
              rm -f install.sh
              export PATH="$PATH:$HOME/bin"

              # Execute projects using generic functionality
              cd $GENERIC_PROJECTS_DIR/tar; bazel build //:my-tar
              cd $GENERIC_PROJECTS_DIR/rules/print-message; bazel build //:nothing
              cd $GENERIC_PROJECTS_DIR/rules/write-file; bazel build //:gen

              # Execute Java-based projects
              cd $JAVA_PROJECTS_DIR/single-package; bazel build //:hello-world