name: DCG

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Specify the version of Java you need
          distribution: 'zulu'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Fetch master branch
        run: git fetch origin master

      - name: Run Bazel Coverage
        run: |
          cd java/spring-boot
          bazel coverage --instrumentation_filter="^//src[/:]" //src/test/func:sample_code_test --combined_report=lcov
          LATEST_MASTER_COMMIT=$(git rev-parse origin/master)
          python script-coverage.py --commit_id "$LATEST_MASTER_COMMIT"
          genhtml --branch-coverage --output genhtml bazel-out/_coverage/filtered_coverage_report.dat
          
