name: DCG

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Checkout from PR branch  
        uses: actions/checkout@v2
        with: 
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Build and Deploy Script
        working-directory: ${{ github.workspace }}/PROJECT_FOLDER
        run: |
          cd java/spring-boot
          
